/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SampleImport } from './routes/sample'
import { Route as LoginImport } from './routes/login'

// Create Virtual Routes

const ServersLazyImport = createFileRoute('/servers')()
const IndexLazyImport = createFileRoute('/')()
const ServersServerIdChannelsChannelIdLazyImport = createFileRoute(
  '/servers/$serverId/channels/$channelId',
)()

// Create/Update Routes

const ServersLazyRoute = ServersLazyImport.update({
  path: '/servers',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/servers.lazy').then((d) => d.Route))

const SampleRoute = SampleImport.update({
  path: '/sample',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ServersServerIdChannelsChannelIdLazyRoute =
  ServersServerIdChannelsChannelIdLazyImport.update({
    path: '/$serverId/channels/$channelId',
    getParentRoute: () => ServersLazyRoute,
  } as any).lazy(() =>
    import('./routes/servers.$serverId.channels.$channelId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleImport
      parentRoute: typeof rootRoute
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersLazyImport
      parentRoute: typeof rootRoute
    }
    '/servers/$serverId/channels/$channelId': {
      id: '/servers/$serverId/channels/$channelId'
      path: '/$serverId/channels/$channelId'
      fullPath: '/servers/$serverId/channels/$channelId'
      preLoaderRoute: typeof ServersServerIdChannelsChannelIdLazyImport
      parentRoute: typeof ServersLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LoginRoute,
  SampleRoute,
  ServersLazyRoute: ServersLazyRoute.addChildren({
    ServersServerIdChannelsChannelIdLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/sample",
        "/servers"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/sample": {
      "filePath": "sample.tsx"
    },
    "/servers": {
      "filePath": "servers.lazy.tsx",
      "children": [
        "/servers/$serverId/channels/$channelId"
      ]
    },
    "/servers/$serverId/channels/$channelId": {
      "filePath": "servers.$serverId.channels.$channelId.lazy.tsx",
      "parent": "/servers"
    }
  }
}
ROUTE_MANIFEST_END */
