/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpacesSpaceIdChannelsChannelIdImport } from './routes/spaces/$spaceId/channels/$channelId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SpacesSpaceIdChannelsChannelIdRoute =
  SpacesSpaceIdChannelsChannelIdImport.update({
    path: '/spaces/$spaceId/channels/$channelId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/spaces/$spaceId/channels/$channelId': {
      id: '/spaces/$spaceId/channels/$channelId'
      path: '/spaces/$spaceId/channels/$channelId'
      fullPath: '/spaces/$spaceId/channels/$channelId'
      preLoaderRoute: typeof SpacesSpaceIdChannelsChannelIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  SpacesSpaceIdChannelsChannelIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/spaces/$spaceId/channels/$channelId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/spaces/$spaceId/channels/$channelId": {
      "filePath": "spaces/$spaceId/channels/$channelId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
